export interface EmojiGroup {
  id: string;
  label: string;
  icon: string;
  emojis: string[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    "id": "smileys",
    "label": "Mặt & cảm xúc",
    "icon": "😀",
    "emojis": [
      "😀",
      "😁",
      "😂",
      "😃",
      "😄",
      "😅",
      "😆",
      "😇",
      "😈",
      "😉",
      "😊",
      "😋",
      "😌",
      "😍",
      "😎",
      "😏",
      "😐",
      "😑",
      "😒",
      "😓",
      "😔",
      "😕",
      "😖",
      "😗",
      "😘",
      "😙",
      "😚",
      "😛",
      "😜",
      "😝",
      "😞",
      "😟",
      "😠",
      "😡",
      "😢",
      "😣",
      "😤",
      "😥",
      "😦",
      "😧",
      "😨",
      "😩",
      "😪",
      "😫",
      "😬",
      "😭",
      "😮",
      "😯",
      "😰",
      "😱",
      "😲",
      "😳",
      "😴",
      "😵",
      "😶",
      "😷",
      "😸",
      "😹",
      "😺",
      "😻",
      "😼",
      "😽",
      "😾",
      "😿",
      "🙀",
      "🙁",
      "🙂",
      "🙃",
      "🙄",
      "🙅",
      "🙆",
      "🙇",
      "🙈",
      "🙉",
      "🙊",
      "🙋",
      "🙌",
      "🙍",
      "🙎",
      "🙏"
    ]
  },
  {
    "id": "people",
    "label": "Người & cơ thể",
    "icon": "🧑",
    "emojis": [
      "👀",
      "👁",
      "👂",
      "👃",
      "👄",
      "👅",
      "👆",
      "👇",
      "👈",
      "👉",
      "👊",
      "👋",
      "👌",
      "👍",
      "👎",
      "👏",
      "👐",
      "👑",
      "👒",
      "👓",
      "👔",
      "👕",
      "👖",
      "👗",
      "👘",
      "👙",
      "👚",
      "👛",
      "👜",
      "👝",
      "👞",
      "👟",
      "👠",
      "👡",
      "👢",
      "👣",
      "👤",
      "👥",
      "👦",
      "👧",
      "👨",
      "👩",
      "👪",
      "👫",
      "👬",
      "👭",
      "👮",
      "👯",
      "👰",
      "👱",
      "👲",
      "👳",
      "👴",
      "👵",
      "👶",
      "👷",
      "👸",
      "👹",
      "👺",
      "👻",
      "👼",
      "👽",
      "👾",
      "👿",
      "💀",
      "💁",
      "💂",
      "💃",
      "💄",
      "💅",
      "💆",
      "💇",
      "💈",
      "💉",
      "💊",
      "💋",
      "💌",
      "💍",
      "💎",
      "💏",
      "💐",
      "💑",
      "💒",
      "💓",
      "💔",
      "💕",
      "💖",
      "💗",
      "💘",
      "💙",
      "💚",
      "💛",
      "💜",
      "💝",
      "💞",
      "💟",
      "🧠",
      "🧡",
      "🧒",
      "🧓",
      "🧔",
      "🧕",
      "🧖",
      "🧗",
      "🧘",
      "🧙",
      "🧚",
      "🧛",
      "🧜",
      "🧝",
      "🧞",
      "🧟",
      "🩰",
      "🩱",
      "🩲",
      "🩳",
      "🩴",
      "🩵",
      "🩶",
      "🩷",
      "🩸",
      "🩹",
      "🩺",
      "🩻",
      "🩼",
      "🫀",
      "🫁",
      "🫂",
      "🫃",
      "🫄",
      "🫅",
      "🫠",
      "🫡",
      "🫢",
      "🫣",
      "🫤",
      "🫥",
      "🫦",
      "🫧",
      "🫨",
      "🫰",
      "🫱",
      "🫲",
      "🫳",
      "🫴",
      "🫵",
      "🫶",
      "🫷",
      "🫸"
    ]
  },
  {
    "id": "nature",
    "label": "Động vật & thiên nhiên",
    "icon": "🐶",
    "emojis": [
      "🐀",
      "🐁",
      "🐂",
      "🐃",
      "🐄",
      "🐅",
      "🐆",
      "🐇",
      "🐈",
      "🐉",
      "🐊",
      "🐋",
      "🐌",
      "🐍",
      "🐎",
      "🐏",
      "🐐",
      "🐑",
      "🐒",
      "🐓",
      "🐔",
      "🐕",
      "🐖",
      "🐗",
      "🐘",
      "🐙",
      "🐚",
      "🐛",
      "🐜",
      "🐝",
      "🐞",
      "🐟",
      "🐠",
      "🐡",
      "🐢",
      "🐣",
      "🐤",
      "🐥",
      "🐦",
      "🐧",
      "🐨",
      "🐩",
      "🐪",
      "🐫",
      "🐬",
      "🐭",
      "🐮",
      "🐯",
      "🐰",
      "🐱",
      "🐲",
      "🐳",
      "🐴",
      "🐵",
      "🐶",
      "🐷",
      "🐸",
      "🐹",
      "🐺",
      "🐻",
      "🐼",
      "🐽",
      "🐾",
      "🐿",
      "🪰",
      "🪱",
      "🪲",
      "🪳",
      "🪴",
      "🪵",
      "🪶",
      "🪷",
      "🪸",
      "🪹",
      "🪺",
      "🪻",
      "🪼",
      "🪽",
      "🪿",
      "🫎",
      "🫏",
      "🌱",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌷",
      "🌸",
      "🌹",
      "🌺",
      "🌻",
      "🌼",
      "🌽",
      "🌾",
      "🌿",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🍄",
      "🌀",
      "🌁",
      "🌂",
      "🌃",
      "🌄",
      "🌅",
      "🌆",
      "🌇",
      "🌈",
      "🌉",
      "🌊",
      "🌋",
      "🌌",
      "🌍",
      "🌎",
      "🌏",
      "🌐",
      "🌑",
      "🌒",
      "🌓",
      "🌔",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌙",
      "🌚",
      "🌛",
      "🌜",
      "🌝",
      "🌞",
      "🌟",
      "🌠",
      "🌡",
      "🌤",
      "🌥",
      "🌦",
      "🌧",
      "🌨",
      "🌩",
      "🌪",
      "🌫",
      "🌬"
    ]
  },
  {
    "id": "food",
    "label": "Đồ ăn & thức uống",
    "icon": "🍔",
    "emojis": [
      "🌭",
      "🌮",
      "🌯",
      "🌰",
      "🌶",
      "🍅",
      "🍆",
      "🍇",
      "🍈",
      "🍉",
      "🍊",
      "🍋",
      "🍌",
      "🍍",
      "🍎",
      "🍏",
      "🍐",
      "🍑",
      "🍒",
      "🍓",
      "🍔",
      "🍕",
      "🍖",
      "🍗",
      "🍘",
      "🍙",
      "🍚",
      "🍛",
      "🍜",
      "🍝",
      "🍞",
      "🍟",
      "🍠",
      "🍡",
      "🍢",
      "🍣",
      "🍤",
      "🍥",
      "🍦",
      "🍧",
      "🍨",
      "🍩",
      "🍪",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🍯",
      "🍰",
      "🍱",
      "🍲",
      "🍳",
      "🍴",
      "🍵",
      "🍶",
      "🍷",
      "🍸",
      "🍹",
      "🍺",
      "🍻",
      "🍼",
      "🍽",
      "🍾",
      "🍿",
      "🥐",
      "🥑",
      "🥒",
      "🥓",
      "🥔",
      "🥕",
      "🥖",
      "🥗",
      "🥘",
      "🥙",
      "🥚",
      "🥛",
      "🥜",
      "🥝",
      "🥞",
      "🥟",
      "🥠",
      "🥡",
      "🥢",
      "🥣",
      "🥤",
      "🥥",
      "🥦",
      "🥧",
      "🥨",
      "🥩",
      "🥪",
      "🥫",
      "🥬",
      "🥭",
      "🥮",
      "🥯",
      "🧀",
      "🧁",
      "🧂",
      "🧃",
      "🧄",
      "🧅",
      "🧆",
      "🧇",
      "🧈",
      "🧉",
      "🧊",
      "🧋",
      "🫐",
      "🫑",
      "🫒",
      "🫓",
      "🫔",
      "🫕",
      "🫖",
      "🫗",
      "🫘",
      "🫙",
      "🫚",
      "🫛"
    ]
  },
  {
    "id": "activity",
    "label": "Hoạt động & thể thao",
    "icon": "⚽",
    "emojis": [
      "⚽",
      "⚾",
      "🎾",
      "🏀",
      "🏐",
      "🏈",
      "🏉",
      "🎱",
      "🎳",
      "🏏",
      "🏑",
      "🏒",
      "🏓",
      "🏸",
      "🥊",
      "🥋",
      "🥅",
      "⛳",
      "⛸",
      "🎣",
      "🤿",
      "🎽",
      "🎿",
      "🛷",
      "🥌",
      "🎯",
      "🪀",
      "🪁",
      "🎮",
      "🕹",
      "🎰",
      "🎲",
      "🧩",
      "🎪",
      "🎨",
      "🎭",
      "🎤",
      "🎧",
      "🎼",
      "🎹",
      "🥁",
      "🎷",
      "🎺",
      "🎸",
      "🪕",
      "🎻",
      "🪗",
      "🪘",
      "🎬",
      "🏹",
      "🏇",
      "🧗",
      "🚴",
      "🚵",
      "🏃",
      "🚶",
      "🏋",
      "🤺",
      "🤼",
      "🤽",
      "🤾",
      "🏌",
      "🏄",
      "🏊",
      "🥇",
      "🥈",
      "🥉",
      "🏆",
      "🏅",
      "🏵",
      "🎫",
      "🎟",
      "🎪",
      "🎠",
      "🎡",
      "🎢",
      "🛹",
      "🛼",
      "🪂",
      "🪃"
    ]
  },
  {
    "id": "travel",
    "label": "Du lịch & phương tiện",
    "icon": "🚗",
    "emojis": [
      "🚀",
      "🚁",
      "🚂",
      "🚃",
      "🚄",
      "🚅",
      "🚆",
      "🚇",
      "🚈",
      "🚉",
      "🚊",
      "🚋",
      "🚌",
      "🚍",
      "🚎",
      "🚏",
      "🚐",
      "🚑",
      "🚒",
      "🚓",
      "🚔",
      "🚕",
      "🚖",
      "🚗",
      "🚘",
      "🚙",
      "🚚",
      "🚛",
      "🚜",
      "🚝",
      "🚞",
      "🚟",
      "🚠",
      "🚡",
      "🚢",
      "🚣",
      "🚤",
      "🛳",
      "🛴",
      "🛵",
      "🏍",
      "🏎",
      "🚲",
      "🛶",
      "🛸",
      "🛺",
      "🛻",
      "🛫",
      "🛬",
      "🛰",
      "🗺",
      "🗻",
      "🗼",
      "🗽",
      "🗾",
      "🗿",
      "🏠",
      "🏡",
      "🏢",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏧",
      "🏨",
      "🏩",
      "🏪",
      "🏫",
      "🏬",
      "🏭",
      "🏮",
      "🏯",
      "🏰",
      "⛩",
      "⛪",
      "🕌",
      "🕍",
      "🕋",
      "🛕",
      "🏖",
      "🏕",
      "🏜",
      "🏝",
      "🏞",
      "🏟"
    ]
  },
  {
    "id": "objects",
    "label": "Đồ vật",
    "icon": "💡",
    "emojis": [
      "💡",
      "🔦",
      "🏮",
      "🕯",
      "🪔",
      "📱",
      "📲",
      "☎",
      "📞",
      "📟",
      "📠",
      "🔋",
      "🔌",
      "💻",
      "🖥",
      "🖨",
      "⌨",
      "🖱",
      "🖲",
      "💽",
      "💾",
      "💿",
      "📀",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽",
      "📻",
      "📺",
      "📼",
      "🧭",
      "⏱",
      "⏲",
      "⏰",
      "🕰",
      "⌛",
      "⏳",
      "📡",
      "🔍",
      "🔎",
      "🔬",
      "🔭",
      "🔮",
      "🧿",
      "🪬",
      "📿",
      "💎",
      "💰",
      "💴",
      "💵",
      "💶",
      "💷",
      "💳",
      "🧾",
      "✉",
      "📩",
      "📨",
      "📧",
      "📦",
      "📫",
      "📪",
      "📬",
      "📭",
      "📮",
      "📝",
      "📄",
      "📃",
      "📑",
      "📊",
      "📈",
      "📉",
      "📜",
      "📋",
      "📅",
      "📆",
      "🗂",
      "📁",
      "📂",
      "🗃",
      "🗄",
      "🗑",
      "🔒",
      "🔓",
      "🔏",
      "🔐",
      "🔑",
      "🗝",
      "🔨",
      "🛠",
      "⛏",
      "🔧",
      "🔩",
      "⚙",
      "🧱",
      "⛓",
      "🧲",
      "🔫",
      "💣",
      "🧨",
      "🪓",
      "🔪",
      "🗡",
      "⚔",
      "🛡",
      "🚬",
      "⚰",
      "⚱",
      "🏺",
      "🔮",
      "📿",
      "💈",
      "🧪",
      "🧫",
      "🧬",
      "🔬",
      "🔭",
      "📡",
      "💉",
      "💊",
      "🩹",
      "🩺",
      "🚪",
      "🪞",
      "🪟",
      "🛏",
      "🛋",
      "🪑",
      "🚽",
      "🚿",
      "🛁",
      "🪤",
      "🪒",
      "🧴",
      "🧷",
      "🧹",
      "🧺",
      "🧻",
      "🧼",
      "🧽",
      "🧯",
      "🛒",
      "🧳",
      "🛎"
    ]
  },
  {
    "id": "symbols",
    "label": "Biểu tượng",
    "icon": "❤️",
    "emojis": [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮",
      "✝",
      "☪",
      "🕉",
      "☸",
      "✡",
      "🔯",
      "🕎",
      "☯",
      "☦",
      "🛐",
      "⛎",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "🆔",
      "⚛",
      "☣",
      "☢",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🈷",
      "✴",
      "🆚",
      "💮",
      "🉐",
      "㊙",
      "㊗",
      "🈴",
      "🈵",
      "🈹",
      "🈲",
      "🅰",
      "🅱",
      "🆎",
      "🆑",
      "🅾",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "💢",
      "♨",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      "🚭",
      "❗",
      "❕",
      "❓",
      "❔",
      "‼",
      "⁉",
      "🔅",
      "🔆",
      "〽",
      "⚠️",
      "🚸",
      "🔱",
      "⚜",
      "🔰",
      "♻",
      "✅",
      "🈯",
      "💹",
      "❇",
      "✳",
      "❎",
      "🌐",
      "💠",
      "Ⓜ",
      "🌀",
      "💤",
      "🏧",
      "🚾",
      "♿",
      "🅿",
      "🈳",
      "🈂",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "🚹",
      "🚺",
      "🚼",
      "🚻",
      "🚮",
      "🎦",
      "📶",
      "🈁",
      "🆖",
      "🆗",
      "🆙",
      "🆒",
      "🆕",
      "🆓",
      "🔟",
      "🔢",
      "🔣",
      "🔤",
      "🔡",
      "🔠",
      "ℹ",
      "📶",
      "▶",
      "◀",
      "🔼",
      "🔽",
      "⏩",
      "⏪",
      "⏫",
      "⏬",
      "➡️",
      "⬅️",
      "⬆️",
      "⬇️",
      "↗️",
      "↘️",
      "↙️",
      "↖️",
      "↕️",
      "↔️",
      "🔄",
      "↪️",
      "↩️",
      "⤴️",
      "⤵️",
      "🔀",
      "🔁",
      "🔂",
      "➕",
      "➖",
      "➗",
      "✖️",
      "♾",
      "💲",
      "💱",
      "™",
      "©",
      "®",
      "👁️‍🗨️",
      "🔘",
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "⚫",
      "⚪",
      "🟤",
      "🔺",
      "🔻",
      "🔸",
      "🔹",
      "🔶",
      "🔷",
      "🔳",
      "🔲",
      "▪️",
      "▫️",
      "◾",
      "◽",
      "◼️",
      "◻️",
      "⬛",
      "⬜",
      "🔈",
      "🔉",
      "🔊",
      "🔇",
      "🔔",
      "🔕",
      "📣",
      "📢",
      "💬",
      "💭",
      "🗯",
      "♠️",
      "♣️",
      "♥️",
      "♦️",
      "🃏",
      "🎴"
    ]
  },
  {
    "id": "flags",
    "label": "Cờ các quốc gia",
    "icon": "🇻🇳",
    "emojis": [
      "🇻🇳",
      "🇺🇸",
      "🇬🇧",
      "🇯🇵",
      "🇰🇷",
      "🇨🇳",
      "🇫🇷",
      "🇩🇪",
      "🇮🇹",
      "🇪🇸",
      "🇷🇺",
      "🇧🇷",
      "🇨🇦",
      "🇦🇺",
      "🇮🇳",
      "🇹🇭",
      "🇸🇬",
      "🇲🇾",
      "🇮🇩",
      "🇵🇭",
      "🇱🇦",
      "🇰🇭",
      "🇲🇲",
      "🇧🇳",
      "🇵🇹",
      "🇲🇽",
      "🇦🇷",
      "🇨🇭",
      "🇸🇪",
      "🇳🇴",
      "🇩🇰",
      "🇫🇮",
      "🇳🇱",
      "🇧🇪",
      "🇦🇹",
      "🇬🇷",
      "🇹🇷",
      "🇸🇦",
      "🇦🇪",
      "🇪🇬",
      "🇿🇦",
      "🇳🇿",
      "🏳️",
      "🏴",
      "🏁",
      "🚩",
      "🎌",
      "🏴‍☠️",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🇦",
      "🇧",
      "🇨",
      "🇩",
      "🇪",
      "🇫",
      "🇬",
      "🇭",
      "🇮",
      "🇯",
      "🇰",
      "🇱",
      "🇲",
      "🇳",
      "🇴",
      "🇵",
      "🇶",
      "🇷",
      "🇸",
      "🇹",
      "🇺",
      "🇻",
      "🇼",
      "🇽",
      "🇾",
      "🇿"
    ]
  }
];

export const EMOJI_NAMES: Record<string, string> = {
  "😀": "Grinning Face (Cười tươi)",
  "😁": "Grinning Face with Smiling Eyes (Cười híp mắt)",
  "😂": "Face with Tears of Joy (Cười ra nước mắt)",
  "😃": "Smiling Face with Open Mouth (Cười rạng rỡ)",
  "😄": "Smiling Face with Open Mouth & Eyes (Cười tươi vui vẻ)",
  "😅": "Smiling Face with Cold Sweat (Cười trừ toát mồ hôi)",
  "😆": "Grinning Squinting Face (Cười ngặt nghẽo)",
  "😇": "Smiling Face with Halo (Thiên thần hiền lành)",
  "😈": "Smiling Face with Horns (Quỷ nhỏ tinh nghịch)",
  "😉": "Winking Face (Nháy mắt)",
  "😊": "Smiling Face with Smiling Eyes (Mỉm cười ấm áp)",
  "😋": "Face Savoring Food (Thèm ăn ngon)",
  "😌": "Relieved Face (Thư thái nhẹ nhõm)",
  "😍": "Heart Eyes (Mắt trái tim yêu thích)",
  "😎": "Sunglasses (Ngầu sành điệu)",
  "😏": "Smirking Face (Cười nhếch mép)",
  "😐": "Neutral Face (Mặt vô cảm)",
  "😑": "Expressionless Face (Không cảm xúc)",
  "😒": "Unamused Face (Không hài lòng)",
  "😓": "Face with Cold Sweat (Thở dài toát mồ hôi)",
  "😔": "Pensive Face (Trầm ngâm buồn bã)",
  "😕": "Confused Face (Bối rối phân vân)",
  "😖": "Confounded Face (Bực bội luống cuống)",
  "😗": "Kissing Face (Chu môi hôn)",
  "😘": "Face Blowing a Kiss (Hôn gió gửi yêu thương)",
  "😙": "Kissing Face with Smiling Eyes (Hôn mỉm cười)",
  "😚": "Kissing Face with Closed Eyes (Hôn nhắm mắt)",
  "😛": "Face with Tongue (Lè lưỡi trêu đùa)",
  "😜": "Winking Face with Tongue (Lè lưỡi nháy mắt)",
  "😝": "Squinting Face with Tongue (Lè lưỡi tít mắt)",
  "😞": "Disappointed Face (Thất vọng)",
  "😟": "Worried Face (Lo lắng bồn chồn)",
  "😠": "Angry Face (Tức giận)",
  "😡": "Pouting Face (Giận dữ đỏ mặt)",
  "😢": "Crying Face (Rơi nước mắt khóc)",
  "😣": "Persevering Face (Cố gắng chịu đựng)",
  "😤": "Face with Steam from Nose (Hậm hực khinh khỉnh)",
  "😥": "Sad but Relieved (Hú hồn nhẹ nhõm)",
  "😦": "Frowning Face with Open Mouth (Há hốc sững sờ)",
  "😧": "Anguished Face (Đau buồn khổ sở)",
  "😨": "Fearful Face (Sợ hãi run rẩy)",
  "😩": "Weary Face (Mệt mỏi bất lực)",
  "😪": "Sleepy Face (Buồn ngủ chảy nước dãi)",
  "😫": "Tired Face (Kiệt sức mệt lử)",
  "😬": "Grimacing Face (Gượng gạo nhăn nhó)",
  "😭": "Loudly Crying Face (Khóc lóc thảm thiết)",
  "😮": "Face with Open Mouth (Ngạc nhiên tròn mắt)",
  "😯": "Hushed Face (Bất ngờ sững sờ)",
  "😰": "Anxious Face with Sweat (Lo sợ toát mồ hôi lạnh)",
  "😱": "Face Screaming in Fear (Hét lên vì kinh hãi)",
  "😲": "Astonished Face (Kinh ngạc sửng sốt)",
  "😳": "Flushed Face (Ngại ngùng đỏ ửng mặt)",
  "😴": "Sleeping Face (Đang ngủ khò)",
  "😵": "Dizzy Face (Chóng mặt hoa mắt)",
  "😶": "Face Without Mouth (Không nói nên lời)",
  "😷": "Medical Mask (Đeo khẩu trang)",
  "😸": "Grinning Cat Face (Mèo cười toe toét)",
  "😹": "Cat with Tears of Joy (Mèo cười ra nước mắt)",
  "😺": "Smiling Cat Face (Mèo mỉm cười)",
  "😻": "Smiling Cat with Heart Eyes (Mèo mắt trái tim)",
  "😼": "Cat with Wry Smile (Mèo cười đểu)",
  "😽": "Kissing Cat (Mèo hôn âu yếm)",
  "😾": "Pouting Cat (Mèo dỗi hờn giận dữ)",
  "😿": "Crying Cat (Mèo khóc thút thít)",
  "🙀": "Weary Cat (Mèo hoảng hốt hốt hoảng)",
  "🙁": "Slightly Frowning Face (Hơi buồn hơi xịu)",
  "🙂": "Slightly Smiling Face (Mỉm cười nhẹ)",
  "🙃": "Upside-Down Face (Mặt lộn ngược ngộ nghĩnh)",
  "🙄": "Face with Rolling Eyes (Đảo mắt ngán ngẩm)",
  "🙅": "Person Gesturing No (Không đồng ý ra hiệu x)",
  "🙆": "Person Gesturing OK (Đồng ý ra hiệu ok)",
  "🙇": "Person Bowing (Cúi đầu tạ lỗi cảm ơn)",
  "🙈": "See-No-Evil Monkey (Khỉ bịt mắt không nhìn)",
  "🙉": "Hear-No-Evil Monkey (Khỉ bịt tai không nghe)",
  "🙊": "Speak-No-Evil Monkey (Khỉ bịt miệng không nói)",
  "🙋": "Person Raising Hand (Giơ tay phát biểu)",
  "🙌": "Raising Hands (Nâng tay ăn mừng)",
  "🙍": "Person Frowning (Người cau mày)",
  "🙎": "Person Pouting (Người hờn dỗi)",
  "🙏": "Folded Hands (Chắp tay cầu nguyện cảm ơn)",
  "🫠": "Melting Face (Mặt tan chảy bất lực)",
  "🫡": "Saluting Face (Chào kính trọng)",
  "🫢": "Face with Open Eyes and Hand Over Mouth (Ngạc nhiên bịt miệng)",
  "🫣": "Face with Peeking Eye (Mặt hé mắt nhìn lén)",
  "🫤": "Face with Diagonal Mouth (Cười méo miệng ngờ vực)",
  "🫥": "Dotted Line Face (Mặt tàng hình nhạt nhòa)",
  "🫦": "Biting Lip (Cắn môi quyến rũ)",
  "🫧": "Bubbles (Bong bóng lấp lánh)",
  "🫨": "Shaking Face (Mặt rung chuyển chấn động)",
  "🫰": "Hand with Index and Thumb Crossed (Bắn tim ngón tay)",
  "🫱": "Rightwards Hand (Bàn tay chỉ sang phải)",
  "🫲": "Leftwards Hand (Bàn tay chỉ sang trái)",
  "🫳": "Palm Down Hand (Lòng bàn tay úp)",
  "🫴": "Palm Up Hand (Lòng bàn tay ngửa)",
  "🫵": "Index Pointing at Viewer (Ngón tay chỉ bạn)",
  "🫶": "Heart Hands (Đôi tay tạo hình trái tim)",
  "🫷": "Leftwards Pushing Hand (Bàn tay đẩy sang trái)",
  "🫸": "Rightwards Pushing Hand (Bàn tay đẩy sang phải)",
  "👀": "Eyes (Đôi mắt)",
  "👁": "Eye (Con mắt)",
  "👂": "Ear (Tai)",
  "👃": "Nose (Mũi)",
  "👄": "Mouth (Đôi môi)",
  "👅": "Tongue (Chiếc lưỡi)",
  "👆": "Index Pointing Up (Chỉ lên trên)",
  "👇": "Index Pointing Down (Chỉ xuống dưới)",
  "👈": "Index Pointing Left (Chỉ sang trái)",
  "👉": "Index Pointing Right (Chỉ sang phải)",
  "👊": "Fist (Nắm đấm quyết tâm)",
  "👋": "Waving Hand (Vẫy tay chào)",
  "👌": "OK Hand (Dấu hiệu OK)",
  "👍": "Thumbs Up (Thích ngón cái số 1)",
  "👎": "Thumbs Down (Không thích)",
  "👏": "Clapping Hands (Vỗ tay chúc mừng)",
  "👐": "Open Hands (Đôi tay mở rộng)",
  "👑": "Crown (Vương miện hoàng gia)",
  "👒": "Woman's Hat (Mũ nữ)",
  "👓": "Eyeglasses (Mắt kính)",
  "👔": "Necktie (Cà vạt công sở)",
  "👕": "T-Shirt (Áo phông thun)",
  "👖": "Jeans (Quần bò jeans)",
  "👗": "Dress (Đầm váy)",
  "👘": "Kimono (Trang phục truyền thống)",
  "👙": "Bikini (Áo tắm bikini)",
  "👚": "Woman's Clothes (Áo nữ thời trang)",
  "👛": "Purse (Ví tiền)",
  "👜": "Handbag (Túi xách tay)",
  "👝": "Pouch (Túi cầm tay)",
  "👞": "Man's Shoe (Giày da nam)",
  "👟": "Sneaker (Giày thể thao sneaker)",
  "👠": "High Heel (Giày cao gót)",
  "👡": "Sandal (Dép sandal nữ)",
  "👢": "Boot (Ủng bốt sành điệu)",
  "👣": "Footprints (Dấu chân)",
  "👤": "Bust in Silhouette (Bóng người)",
  "👥": "Busts in Silhouette (Cộng đồng người)",
  "👦": "Boy (Cậu bé trai)",
  "👧": "Girl (Cô bé gái)",
  "👨": "Man (Đàn ông)",
  "👩": "Woman (Phụ nữ)",
  "👪": "Family (Gia đình)",
  "👫": "Couple (Cặp đôi)",
  "👮": "Police (Cảnh sát)",
  "👰": "Bride (Cô dâu)",
  "👵": "Old Woman (Bà lão)",
  "👴": "Old Man (Ông lão)",
  "👶": "Baby (Em bé)",
  "👸": "Princess (Công chúa)",
  "👻": "Ghost (Hồn ma ma quái)",
  "👼": "Baby Angel (Thiên thần)",
  "👽": "Alien (Người ngoài hành tinh)",
  "💀": "Skull (Đầu lâu sọ người)",
  "💃": "Dancer (Vũ công khiêu vũ)",
  "💄": "Lipstick (Son môi trang điểm)",
  "💅": "Nail Polish (Sơn móng tay)",
  "💉": "Syringe (Kim tiêm y tế)",
  "💊": "Pill (Viên thuốc)",
  "💋": "Kiss Mark (Vết son môi)",
  "💌": "Love Letter (Thư tình)",
  "💍": "Ring (Nhẫn kim cương cưới)",
  "💎": "Gem Stone (Viên đá quý kim cương)",
  "💐": "Bouquet (Bó hoa tươi)",
  "💓": "Beating Heart (Trái tim rộn ràng)",
  "💔": "Broken Heart (Trái tim tan vỡ)",
  "💕": "Two Hearts (Hai trái tim)",
  "💖": "Sparkling Heart (Trái tim lấp lánh)",
  "💗": "Growing Heart (Trái tim rung động)",
  "💘": "Heart with Arrow (Trái tim thần tình yêu)",
  "💙": "Blue Heart (Trái tim xanh dương)",
  "💚": "Green Heart (Trái tim xanh lá)",
  "💛": "Yellow Heart (Trái tim vàng)",
  "💜": "Purple Heart (Trái tim tím)",
  "💝": "Heart with Ribbon (Hộp quà trái tim)",
  "💞": "Revolving Hearts (Những trái tim xoay quanh)",
  "🧠": "Brain (Bộ não tư duy trí tuệ)",
  "🧡": "Orange Heart (Trái tim màu cam)",
  "🧘": "Yoga (Thiền định yoga)",
  "🧜": "Merperson (Người cá biển cả)",
  "🧟": "Zombie (Xác sống)",
  "🩸": "Blood (Giọt máu hiến máu)",
  "🩹": "Bandage (Băng gạc vết thương)",
  "🩺": "Stethoscope (Ống nghe bác sĩ)",
  "🩻": "X-Ray (Chụp X-quang)",
  "🩼": "Crutch (Cây nạng)",
  "🫀": "Heart Organ (Cơ quan tim)",
  "🫁": "Lungs (Lá phổi)",
  "🫂": "Hugging (Cái ôm ấm áp)",
  "🌭": "Hot Dog (Bánh mì xúc xích)",
  "🍔": "Hamburger (Burger kẹp thịt)",
  "🍕": "Pizza (Bánh pizza Ý)",
  "🍜": "Ramen (Mì ramen nóng hổi)",
  "🍣": "Sushi (Sushi cá hồi)",
  "🍦": "Ice Cream (Kem mát lạnh)",
  "☕": "Coffee (Tách cà phê)",
  "🍺": "Beer (Cốc bia)",
  "🍷": "Wine (Rượu vang)",
  "🍉": "Watermelon (Dưa hấu mát lạnh)",
  "🍎": "Red Apple (Táo đỏ)",
  "🍓": "Strawberry (Dâu tây)",
  "🥭": "Mango (Xoài ngọt)",
  "🧋": "Bubble Tea (Trà sữa trân châu)",
  "🌸": "Cherry Blossom (Hoa anh đào)",
  "🌹": "Rose (Hoa hồng)",
  "🌻": "Sunflower (Hoa hướng dương)",
  "🍀": "Clover (Cỏ 4 lá may mắn)",
  "🐶": "Dog (Chú chó cưng)",
  "🐱": "Cat (Chú mèo con)",
  "🐯": "Tiger (Chúa sơn lâm hổ)",
  "🦁": "Lion (Sư tử oai phong)",
  "🦄": "Unicorn (Kỳ lân thần tiên)",
  "🦋": "Butterfly (Chú bướm xinh)",
  "🐬": "Dolphin (Cá heo thông minh)",
  "⭐": "Star (Ngôi sao)",
  "🌟": "Glowing Star (Sao phát sáng)",
  "✨": "Sparkles (Lấp lánh)",
  "⚡": "Lightning (Sấm sét)",
  "🔥": "Fire (Ngọn lửa nóng)",
  "🇻🇳": "Vietnam (Quốc kỳ Việt Nam)",
  "🇺🇸": "United States (Quốc kỳ Mỹ)",
  "🇬🇧": "United Kingdom (Quốc kỳ Anh)",
  "🇯🇵": "Japan (Quốc kỳ Nhật Bản)",
  "🇰🇷": "South Korea (Quốc kỳ Hàn Quốc)",
  "🇫🇷": "France (Quốc kỳ Pháp)",
  "🇩🇪": "Germany (Quốc kỳ Đức)",
  "🇨🇳": "China (Quốc kỳ Trung Quốc)",
  "🚩": "Flag (Cờ tam giác đỏ)",
  "🏁": "Chequered Flag (Cờ đích ca-rô)",
  "👬": "Người & cơ thể: 👬",
  "👭": "Người & cơ thể: 👭",
  "👯": "Người & cơ thể: 👯",
  "👱": "Người & cơ thể: 👱",
  "👲": "Người & cơ thể: 👲",
  "👳": "Người & cơ thể: 👳",
  "👷": "Người & cơ thể: 👷",
  "👹": "Người & cơ thể: 👹",
  "👺": "Người & cơ thể: 👺",
  "👾": "Người & cơ thể: 👾",
  "👿": "Người & cơ thể: 👿",
  "💁": "Người & cơ thể: 💁",
  "💂": "Người & cơ thể: 💂",
  "💆": "Người & cơ thể: 💆",
  "💇": "Người & cơ thể: 💇",
  "💈": "Người & cơ thể: 💈",
  "💏": "Người & cơ thể: 💏",
  "💑": "Người & cơ thể: 💑",
  "💒": "Người & cơ thể: 💒",
  "💟": "Người & cơ thể: 💟",
  "🧒": "Người & cơ thể: 🧒",
  "🧓": "Người & cơ thể: 🧓",
  "🧔": "Người & cơ thể: 🧔",
  "🧕": "Người & cơ thể: 🧕",
  "🧖": "Người & cơ thể: 🧖",
  "🧗": "Người & cơ thể: 🧗",
  "🧙": "Người & cơ thể: 🧙",
  "🧚": "Người & cơ thể: 🧚",
  "🧛": "Người & cơ thể: 🧛",
  "🧝": "Người & cơ thể: 🧝",
  "🧞": "Người & cơ thể: 🧞",
  "🩰": "Người & cơ thể: 🩰",
  "🩱": "Người & cơ thể: 🩱",
  "🩲": "Người & cơ thể: 🩲",
  "🩳": "Người & cơ thể: 🩳",
  "🩴": "Người & cơ thể: 🩴",
  "🩵": "Người & cơ thể: 🩵",
  "🩶": "Người & cơ thể: 🩶",
  "🩷": "Người & cơ thể: 🩷",
  "🫃": "Người & cơ thể: 🫃",
  "🫄": "Người & cơ thể: 🫄",
  "🫅": "Người & cơ thể: 🫅",
  "🐀": "Động vật & thiên nhiên: 🐀",
  "🐁": "Động vật & thiên nhiên: 🐁",
  "🐂": "Động vật & thiên nhiên: 🐂",
  "🐃": "Động vật & thiên nhiên: 🐃",
  "🐄": "Động vật & thiên nhiên: 🐄",
  "🐅": "Động vật & thiên nhiên: 🐅",
  "🐆": "Động vật & thiên nhiên: 🐆",
  "🐇": "Động vật & thiên nhiên: 🐇",
  "🐈": "Động vật & thiên nhiên: 🐈",
  "🐉": "Động vật & thiên nhiên: 🐉",
  "🐊": "Động vật & thiên nhiên: 🐊",
  "🐋": "Động vật & thiên nhiên: 🐋",
  "🐌": "Động vật & thiên nhiên: 🐌",
  "🐍": "Động vật & thiên nhiên: 🐍",
  "🐎": "Động vật & thiên nhiên: 🐎",
  "🐏": "Động vật & thiên nhiên: 🐏",
  "🐐": "Động vật & thiên nhiên: 🐐",
  "🐑": "Động vật & thiên nhiên: 🐑",
  "🐒": "Động vật & thiên nhiên: 🐒",
  "🐓": "Động vật & thiên nhiên: 🐓",
  "🐔": "Động vật & thiên nhiên: 🐔",
  "🐕": "Động vật & thiên nhiên: 🐕",
  "🐖": "Động vật & thiên nhiên: 🐖",
  "🐗": "Động vật & thiên nhiên: 🐗",
  "🐘": "Động vật & thiên nhiên: 🐘",
  "🐙": "Động vật & thiên nhiên: 🐙",
  "🐚": "Động vật & thiên nhiên: 🐚",
  "🐛": "Động vật & thiên nhiên: 🐛",
  "🐜": "Động vật & thiên nhiên: 🐜",
  "🐝": "Động vật & thiên nhiên: 🐝",
  "🐞": "Động vật & thiên nhiên: 🐞",
  "🐟": "Động vật & thiên nhiên: 🐟",
  "🐠": "Động vật & thiên nhiên: 🐠",
  "🐡": "Động vật & thiên nhiên: 🐡",
  "🐢": "Động vật & thiên nhiên: 🐢",
  "🐣": "Động vật & thiên nhiên: 🐣",
  "🐤": "Động vật & thiên nhiên: 🐤",
  "🐥": "Động vật & thiên nhiên: 🐥",
  "🐦": "Động vật & thiên nhiên: 🐦",
  "🐧": "Động vật & thiên nhiên: 🐧",
  "🐨": "Động vật & thiên nhiên: 🐨",
  "🐩": "Động vật & thiên nhiên: 🐩",
  "🐪": "Động vật & thiên nhiên: 🐪",
  "🐫": "Động vật & thiên nhiên: 🐫",
  "🐭": "Động vật & thiên nhiên: 🐭",
  "🐮": "Động vật & thiên nhiên: 🐮",
  "🐰": "Động vật & thiên nhiên: 🐰",
  "🐲": "Động vật & thiên nhiên: 🐲",
  "🐳": "Động vật & thiên nhiên: 🐳",
  "🐴": "Động vật & thiên nhiên: 🐴",
  "🐵": "Động vật & thiên nhiên: 🐵",
  "🐷": "Động vật & thiên nhiên: 🐷",
  "🐸": "Động vật & thiên nhiên: 🐸",
  "🐹": "Động vật & thiên nhiên: 🐹",
  "🐺": "Động vật & thiên nhiên: 🐺",
  "🐻": "Động vật & thiên nhiên: 🐻",
  "🐼": "Động vật & thiên nhiên: 🐼",
  "🐽": "Động vật & thiên nhiên: 🐽",
  "🐾": "Động vật & thiên nhiên: 🐾",
  "🐿": "Động vật & thiên nhiên: 🐿",
  "🪰": "Động vật & thiên nhiên: 🪰",
  "🪱": "Động vật & thiên nhiên: 🪱",
  "🪲": "Động vật & thiên nhiên: 🪲",
  "🪳": "Động vật & thiên nhiên: 🪳",
  "🪴": "Động vật & thiên nhiên: 🪴",
  "🪵": "Động vật & thiên nhiên: 🪵",
  "🪶": "Động vật & thiên nhiên: 🪶",
  "🪷": "Động vật & thiên nhiên: 🪷",
  "🪸": "Động vật & thiên nhiên: 🪸",
  "🪹": "Động vật & thiên nhiên: 🪹",
  "🪺": "Động vật & thiên nhiên: 🪺",
  "🪻": "Động vật & thiên nhiên: 🪻",
  "🪼": "Động vật & thiên nhiên: 🪼",
  "🪽": "Động vật & thiên nhiên: 🪽",
  "🪿": "Động vật & thiên nhiên: 🪿",
  "🫎": "Động vật & thiên nhiên: 🫎",
  "🫏": "Động vật & thiên nhiên: 🫏",
  "🌱": "Động vật & thiên nhiên: 🌱",
  "🌲": "Động vật & thiên nhiên: 🌲",
  "🌳": "Động vật & thiên nhiên: 🌳",
  "🌴": "Động vật & thiên nhiên: 🌴",
  "🌵": "Động vật & thiên nhiên: 🌵",
  "🌷": "Động vật & thiên nhiên: 🌷",
  "🌺": "Động vật & thiên nhiên: 🌺",
  "🌼": "Động vật & thiên nhiên: 🌼",
  "🌽": "Động vật & thiên nhiên: 🌽",
  "🌾": "Động vật & thiên nhiên: 🌾",
  "🌿": "Động vật & thiên nhiên: 🌿",
  "🍁": "Động vật & thiên nhiên: 🍁",
  "🍂": "Động vật & thiên nhiên: 🍂",
  "🍃": "Động vật & thiên nhiên: 🍃",
  "🍄": "Động vật & thiên nhiên: 🍄",
  "🌀": "Động vật & thiên nhiên: 🌀",
  "🌁": "Động vật & thiên nhiên: 🌁",
  "🌂": "Động vật & thiên nhiên: 🌂",
  "🌃": "Động vật & thiên nhiên: 🌃",
  "🌄": "Động vật & thiên nhiên: 🌄",
  "🌅": "Động vật & thiên nhiên: 🌅",
  "🌆": "Động vật & thiên nhiên: 🌆",
  "🌇": "Động vật & thiên nhiên: 🌇",
  "🌈": "Động vật & thiên nhiên: 🌈",
  "🌉": "Động vật & thiên nhiên: 🌉",
  "🌊": "Động vật & thiên nhiên: 🌊",
  "🌋": "Động vật & thiên nhiên: 🌋",
  "🌌": "Động vật & thiên nhiên: 🌌",
  "🌍": "Động vật & thiên nhiên: 🌍",
  "🌎": "Động vật & thiên nhiên: 🌎",
  "🌏": "Động vật & thiên nhiên: 🌏",
  "🌐": "Động vật & thiên nhiên: 🌐",
  "🌑": "Động vật & thiên nhiên: 🌑",
  "🌒": "Động vật & thiên nhiên: 🌒",
  "🌓": "Động vật & thiên nhiên: 🌓",
  "🌔": "Động vật & thiên nhiên: 🌔",
  "🌕": "Động vật & thiên nhiên: 🌕",
  "🌖": "Động vật & thiên nhiên: 🌖",
  "🌗": "Động vật & thiên nhiên: 🌗",
  "🌘": "Động vật & thiên nhiên: 🌘",
  "🌙": "Động vật & thiên nhiên: 🌙",
  "🌚": "Động vật & thiên nhiên: 🌚",
  "🌛": "Động vật & thiên nhiên: 🌛",
  "🌜": "Động vật & thiên nhiên: 🌜",
  "🌝": "Động vật & thiên nhiên: 🌝",
  "🌞": "Động vật & thiên nhiên: 🌞",
  "🌠": "Động vật & thiên nhiên: 🌠",
  "🌡": "Động vật & thiên nhiên: 🌡",
  "🌤": "Động vật & thiên nhiên: 🌤",
  "🌥": "Động vật & thiên nhiên: 🌥",
  "🌦": "Động vật & thiên nhiên: 🌦",
  "🌧": "Động vật & thiên nhiên: 🌧",
  "🌨": "Động vật & thiên nhiên: 🌨",
  "🌩": "Động vật & thiên nhiên: 🌩",
  "🌪": "Động vật & thiên nhiên: 🌪",
  "🌫": "Động vật & thiên nhiên: 🌫",
  "🌬": "Động vật & thiên nhiên: 🌬",
  "🌮": "Đồ ăn & thức uống: 🌮",
  "🌯": "Đồ ăn & thức uống: 🌯",
  "🌰": "Đồ ăn & thức uống: 🌰",
  "🌶": "Đồ ăn & thức uống: 🌶",
  "🍅": "Đồ ăn & thức uống: 🍅",
  "🍆": "Đồ ăn & thức uống: 🍆",
  "🍇": "Đồ ăn & thức uống: 🍇",
  "🍈": "Đồ ăn & thức uống: 🍈",
  "🍊": "Đồ ăn & thức uống: 🍊",
  "🍋": "Đồ ăn & thức uống: 🍋",
  "🍌": "Đồ ăn & thức uống: 🍌",
  "🍍": "Đồ ăn & thức uống: 🍍",
  "🍏": "Đồ ăn & thức uống: 🍏",
  "🍐": "Đồ ăn & thức uống: 🍐",
  "🍑": "Đồ ăn & thức uống: 🍑",
  "🍒": "Đồ ăn & thức uống: 🍒",
  "🍖": "Đồ ăn & thức uống: 🍖",
  "🍗": "Đồ ăn & thức uống: 🍗",
  "🍘": "Đồ ăn & thức uống: 🍘",
  "🍙": "Đồ ăn & thức uống: 🍙",
  "🍚": "Đồ ăn & thức uống: 🍚",
  "🍛": "Đồ ăn & thức uống: 🍛",
  "🍝": "Đồ ăn & thức uống: 🍝",
  "🍞": "Đồ ăn & thức uống: 🍞",
  "🍟": "Đồ ăn & thức uống: 🍟",
  "🍠": "Đồ ăn & thức uống: 🍠",
  "🍡": "Đồ ăn & thức uống: 🍡",
  "🍢": "Đồ ăn & thức uống: 🍢",
  "🍤": "Đồ ăn & thức uống: 🍤",
  "🍥": "Đồ ăn & thức uống: 🍥",
  "🍧": "Đồ ăn & thức uống: 🍧",
  "🍨": "Đồ ăn & thức uống: 🍨",
  "🍩": "Đồ ăn & thức uống: 🍩",
  "🍪": "Đồ ăn & thức uống: 🍪",
  "🍫": "Đồ ăn & thức uống: 🍫",
  "🍬": "Đồ ăn & thức uống: 🍬",
  "🍭": "Đồ ăn & thức uống: 🍭",
  "🍮": "Đồ ăn & thức uống: 🍮",
  "🍯": "Đồ ăn & thức uống: 🍯",
  "🍰": "Đồ ăn & thức uống: 🍰",
  "🍱": "Đồ ăn & thức uống: 🍱",
  "🍲": "Đồ ăn & thức uống: 🍲",
  "🍳": "Đồ ăn & thức uống: 🍳",
  "🍴": "Đồ ăn & thức uống: 🍴",
  "🍵": "Đồ ăn & thức uống: 🍵",
  "🍶": "Đồ ăn & thức uống: 🍶",
  "🍸": "Đồ ăn & thức uống: 🍸",
  "🍹": "Đồ ăn & thức uống: 🍹",
  "🍻": "Đồ ăn & thức uống: 🍻",
  "🍼": "Đồ ăn & thức uống: 🍼",
  "🍽": "Đồ ăn & thức uống: 🍽",
  "🍾": "Đồ ăn & thức uống: 🍾",
  "🍿": "Đồ ăn & thức uống: 🍿",
  "🥐": "Đồ ăn & thức uống: 🥐",
  "🥑": "Đồ ăn & thức uống: 🥑",
  "🥒": "Đồ ăn & thức uống: 🥒",
  "🥓": "Đồ ăn & thức uống: 🥓",
  "🥔": "Đồ ăn & thức uống: 🥔",
  "🥕": "Đồ ăn & thức uống: 🥕",
  "🥖": "Đồ ăn & thức uống: 🥖",
  "🥗": "Đồ ăn & thức uống: 🥗",
  "🥘": "Đồ ăn & thức uống: 🥘",
  "🥙": "Đồ ăn & thức uống: 🥙",
  "🥚": "Đồ ăn & thức uống: 🥚",
  "🥛": "Đồ ăn & thức uống: 🥛",
  "🥜": "Đồ ăn & thức uống: 🥜",
  "🥝": "Đồ ăn & thức uống: 🥝",
  "🥞": "Đồ ăn & thức uống: 🥞",
  "🥟": "Đồ ăn & thức uống: 🥟",
  "🥠": "Đồ ăn & thức uống: 🥠",
  "🥡": "Đồ ăn & thức uống: 🥡",
  "🥢": "Đồ ăn & thức uống: 🥢",
  "🥣": "Đồ ăn & thức uống: 🥣",
  "🥤": "Đồ ăn & thức uống: 🥤",
  "🥥": "Đồ ăn & thức uống: 🥥",
  "🥦": "Đồ ăn & thức uống: 🥦",
  "🥧": "Đồ ăn & thức uống: 🥧",
  "🥨": "Đồ ăn & thức uống: 🥨",
  "🥩": "Đồ ăn & thức uống: 🥩",
  "🥪": "Đồ ăn & thức uống: 🥪",
  "🥫": "Đồ ăn & thức uống: 🥫",
  "🥬": "Đồ ăn & thức uống: 🥬",
  "🥮": "Đồ ăn & thức uống: 🥮",
  "🥯": "Đồ ăn & thức uống: 🥯",
  "🧀": "Đồ ăn & thức uống: 🧀",
  "🧁": "Đồ ăn & thức uống: 🧁",
  "🧂": "Đồ ăn & thức uống: 🧂",
  "🧃": "Đồ ăn & thức uống: 🧃",
  "🧄": "Đồ ăn & thức uống: 🧄",
  "🧅": "Đồ ăn & thức uống: 🧅",
  "🧆": "Đồ ăn & thức uống: 🧆",
  "🧇": "Đồ ăn & thức uống: 🧇",
  "🧈": "Đồ ăn & thức uống: 🧈",
  "🧉": "Đồ ăn & thức uống: 🧉",
  "🧊": "Đồ ăn & thức uống: 🧊",
  "🫐": "Đồ ăn & thức uống: 🫐",
  "🫑": "Đồ ăn & thức uống: 🫑",
  "🫒": "Đồ ăn & thức uống: 🫒",
  "🫓": "Đồ ăn & thức uống: 🫓",
  "🫔": "Đồ ăn & thức uống: 🫔",
  "🫕": "Đồ ăn & thức uống: 🫕",
  "🫖": "Đồ ăn & thức uống: 🫖",
  "🫗": "Đồ ăn & thức uống: 🫗",
  "🫘": "Đồ ăn & thức uống: 🫘",
  "🫙": "Đồ ăn & thức uống: 🫙",
  "🫚": "Đồ ăn & thức uống: 🫚",
  "🫛": "Đồ ăn & thức uống: 🫛",
  "⚽": "Hoạt động & thể thao: ⚽",
  "⚾": "Hoạt động & thể thao: ⚾",
  "🎾": "Hoạt động & thể thao: 🎾",
  "🏀": "Hoạt động & thể thao: 🏀",
  "🏐": "Hoạt động & thể thao: 🏐",
  "🏈": "Hoạt động & thể thao: 🏈",
  "🏉": "Hoạt động & thể thao: 🏉",
  "🎱": "Hoạt động & thể thao: 🎱",
  "🎳": "Hoạt động & thể thao: 🎳",
  "🏏": "Hoạt động & thể thao: 🏏",
  "🏑": "Hoạt động & thể thao: 🏑",
  "🏒": "Hoạt động & thể thao: 🏒",
  "🏓": "Hoạt động & thể thao: 🏓",
  "🏸": "Hoạt động & thể thao: 🏸",
  "🥊": "Hoạt động & thể thao: 🥊",
  "🥋": "Hoạt động & thể thao: 🥋",
  "🥅": "Hoạt động & thể thao: 🥅",
  "⛳": "Hoạt động & thể thao: ⛳",
  "⛸": "Hoạt động & thể thao: ⛸",
  "🎣": "Hoạt động & thể thao: 🎣",
  "🤿": "Hoạt động & thể thao: 🤿",
  "🎽": "Hoạt động & thể thao: 🎽",
  "🎿": "Hoạt động & thể thao: 🎿",
  "🛷": "Hoạt động & thể thao: 🛷",
  "🥌": "Hoạt động & thể thao: 🥌",
  "🎯": "Hoạt động & thể thao: 🎯",
  "🪀": "Hoạt động & thể thao: 🪀",
  "🪁": "Hoạt động & thể thao: 🪁",
  "🎮": "Hoạt động & thể thao: 🎮",
  "🕹": "Hoạt động & thể thao: 🕹",
  "🎰": "Hoạt động & thể thao: 🎰",
  "🎲": "Hoạt động & thể thao: 🎲",
  "🧩": "Hoạt động & thể thao: 🧩",
  "🎪": "Hoạt động & thể thao: 🎪",
  "🎨": "Hoạt động & thể thao: 🎨",
  "🎭": "Hoạt động & thể thao: 🎭",
  "🎤": "Hoạt động & thể thao: 🎤",
  "🎧": "Hoạt động & thể thao: 🎧",
  "🎼": "Hoạt động & thể thao: 🎼",
  "🎹": "Hoạt động & thể thao: 🎹",
  "🥁": "Hoạt động & thể thao: 🥁",
  "🎷": "Hoạt động & thể thao: 🎷",
  "🎺": "Hoạt động & thể thao: 🎺",
  "🎸": "Hoạt động & thể thao: 🎸",
  "🪕": "Hoạt động & thể thao: 🪕",
  "🎻": "Hoạt động & thể thao: 🎻",
  "🪗": "Hoạt động & thể thao: 🪗",
  "🪘": "Hoạt động & thể thao: 🪘",
  "🎬": "Hoạt động & thể thao: 🎬",
  "🏹": "Hoạt động & thể thao: 🏹",
  "🏇": "Hoạt động & thể thao: 🏇",
  "🚴": "Hoạt động & thể thao: 🚴",
  "🚵": "Hoạt động & thể thao: 🚵",
  "🏃": "Hoạt động & thể thao: 🏃",
  "🚶": "Hoạt động & thể thao: 🚶",
  "🏋": "Hoạt động & thể thao: 🏋",
  "🤺": "Hoạt động & thể thao: 🤺",
  "🤼": "Hoạt động & thể thao: 🤼",
  "🤽": "Hoạt động & thể thao: 🤽",
  "🤾": "Hoạt động & thể thao: 🤾",
  "🏌": "Hoạt động & thể thao: 🏌",
  "🏄": "Hoạt động & thể thao: 🏄",
  "🏊": "Hoạt động & thể thao: 🏊",
  "🥇": "Hoạt động & thể thao: 🥇",
  "🥈": "Hoạt động & thể thao: 🥈",
  "🥉": "Hoạt động & thể thao: 🥉",
  "🏆": "Hoạt động & thể thao: 🏆",
  "🏅": "Hoạt động & thể thao: 🏅",
  "🏵": "Hoạt động & thể thao: 🏵",
  "🎫": "Hoạt động & thể thao: 🎫",
  "🎟": "Hoạt động & thể thao: 🎟",
  "🎠": "Hoạt động & thể thao: 🎠",
  "🎡": "Hoạt động & thể thao: 🎡",
  "🎢": "Hoạt động & thể thao: 🎢",
  "🛹": "Hoạt động & thể thao: 🛹",
  "🛼": "Hoạt động & thể thao: 🛼",
  "🪂": "Hoạt động & thể thao: 🪂",
  "🪃": "Hoạt động & thể thao: 🪃",
  "🚀": "Du lịch & phương tiện: 🚀",
  "🚁": "Du lịch & phương tiện: 🚁",
  "🚂": "Du lịch & phương tiện: 🚂",
  "🚃": "Du lịch & phương tiện: 🚃",
  "🚄": "Du lịch & phương tiện: 🚄",
  "🚅": "Du lịch & phương tiện: 🚅",
  "🚆": "Du lịch & phương tiện: 🚆",
  "🚇": "Du lịch & phương tiện: 🚇",
  "🚈": "Du lịch & phương tiện: 🚈",
  "🚉": "Du lịch & phương tiện: 🚉",
  "🚊": "Du lịch & phương tiện: 🚊",
  "🚋": "Du lịch & phương tiện: 🚋",
  "🚌": "Du lịch & phương tiện: 🚌",
  "🚍": "Du lịch & phương tiện: 🚍",
  "🚎": "Du lịch & phương tiện: 🚎",
  "🚏": "Du lịch & phương tiện: 🚏",
  "🚐": "Du lịch & phương tiện: 🚐",
  "🚑": "Du lịch & phương tiện: 🚑",
  "🚒": "Du lịch & phương tiện: 🚒",
  "🚓": "Du lịch & phương tiện: 🚓",
  "🚔": "Du lịch & phương tiện: 🚔",
  "🚕": "Du lịch & phương tiện: 🚕",
  "🚖": "Du lịch & phương tiện: 🚖",
  "🚗": "Du lịch & phương tiện: 🚗",
  "🚘": "Du lịch & phương tiện: 🚘",
  "🚙": "Du lịch & phương tiện: 🚙",
  "🚚": "Du lịch & phương tiện: 🚚",
  "🚛": "Du lịch & phương tiện: 🚛",
  "🚜": "Du lịch & phương tiện: 🚜",
  "🚝": "Du lịch & phương tiện: 🚝",
  "🚞": "Du lịch & phương tiện: 🚞",
  "🚟": "Du lịch & phương tiện: 🚟",
  "🚠": "Du lịch & phương tiện: 🚠",
  "🚡": "Du lịch & phương tiện: 🚡",
  "🚢": "Du lịch & phương tiện: 🚢",
  "🚣": "Du lịch & phương tiện: 🚣",
  "🚤": "Du lịch & phương tiện: 🚤",
  "🛳": "Du lịch & phương tiện: 🛳",
  "🛴": "Du lịch & phương tiện: 🛴",
  "🛵": "Du lịch & phương tiện: 🛵",
  "🏍": "Du lịch & phương tiện: 🏍",
  "🏎": "Du lịch & phương tiện: 🏎",
  "🚲": "Du lịch & phương tiện: 🚲",
  "🛶": "Du lịch & phương tiện: 🛶",
  "🛸": "Du lịch & phương tiện: 🛸",
  "🛺": "Du lịch & phương tiện: 🛺",
  "🛻": "Du lịch & phương tiện: 🛻",
  "🛫": "Du lịch & phương tiện: 🛫",
  "🛬": "Du lịch & phương tiện: 🛬",
  "🛰": "Du lịch & phương tiện: 🛰",
  "🗺": "Du lịch & phương tiện: 🗺",
  "🗻": "Du lịch & phương tiện: 🗻",
  "🗼": "Du lịch & phương tiện: 🗼",
  "🗽": "Du lịch & phương tiện: 🗽",
  "🗾": "Du lịch & phương tiện: 🗾",
  "🗿": "Du lịch & phương tiện: 🗿",
  "🏠": "Du lịch & phương tiện: 🏠",
  "🏡": "Du lịch & phương tiện: 🏡",
  "🏢": "Du lịch & phương tiện: 🏢",
  "🏣": "Du lịch & phương tiện: 🏣",
  "🏤": "Du lịch & phương tiện: 🏤",
  "🏥": "Du lịch & phương tiện: 🏥",
  "🏦": "Du lịch & phương tiện: 🏦",
  "🏧": "Du lịch & phương tiện: 🏧",
  "🏨": "Du lịch & phương tiện: 🏨",
  "🏩": "Du lịch & phương tiện: 🏩",
  "🏪": "Du lịch & phương tiện: 🏪",
  "🏫": "Du lịch & phương tiện: 🏫",
  "🏬": "Du lịch & phương tiện: 🏬",
  "🏭": "Du lịch & phương tiện: 🏭",
  "🏮": "Du lịch & phương tiện: 🏮",
  "🏯": "Du lịch & phương tiện: 🏯",
  "🏰": "Du lịch & phương tiện: 🏰",
  "⛩": "Du lịch & phương tiện: ⛩",
  "⛪": "Du lịch & phương tiện: ⛪",
  "🕌": "Du lịch & phương tiện: 🕌",
  "🕍": "Du lịch & phương tiện: 🕍",
  "🕋": "Du lịch & phương tiện: 🕋",
  "🛕": "Du lịch & phương tiện: 🛕",
  "🏖": "Du lịch & phương tiện: 🏖",
  "🏕": "Du lịch & phương tiện: 🏕",
  "🏜": "Du lịch & phương tiện: 🏜",
  "🏝": "Du lịch & phương tiện: 🏝",
  "🏞": "Du lịch & phương tiện: 🏞",
  "🏟": "Du lịch & phương tiện: 🏟",
  "💡": "Đồ vật: 💡",
  "🔦": "Đồ vật: 🔦",
  "🕯": "Đồ vật: 🕯",
  "🪔": "Đồ vật: 🪔",
  "📱": "Đồ vật: 📱",
  "📲": "Đồ vật: 📲",
  "☎": "Đồ vật: ☎",
  "📞": "Đồ vật: 📞",
  "📟": "Đồ vật: 📟",
  "📠": "Đồ vật: 📠",
  "🔋": "Đồ vật: 🔋",
  "🔌": "Đồ vật: 🔌",
  "💻": "Đồ vật: 💻",
  "🖥": "Đồ vật: 🖥",
  "🖨": "Đồ vật: 🖨",
  "⌨": "Đồ vật: ⌨",
  "🖱": "Đồ vật: 🖱",
  "🖲": "Đồ vật: 🖲",
  "💽": "Đồ vật: 💽",
  "💾": "Đồ vật: 💾",
  "💿": "Đồ vật: 💿",
  "📀": "Đồ vật: 📀",
  "📷": "Đồ vật: 📷",
  "📸": "Đồ vật: 📸",
  "📹": "Đồ vật: 📹",
  "🎥": "Đồ vật: 🎥",
  "📽": "Đồ vật: 📽",
  "📻": "Đồ vật: 📻",
  "📺": "Đồ vật: 📺",
  "📼": "Đồ vật: 📼",
  "🧭": "Đồ vật: 🧭",
  "⏱": "Đồ vật: ⏱",
  "⏲": "Đồ vật: ⏲",
  "⏰": "Đồ vật: ⏰",
  "🕰": "Đồ vật: 🕰",
  "⌛": "Đồ vật: ⌛",
  "⏳": "Đồ vật: ⏳",
  "📡": "Đồ vật: 📡",
  "🔍": "Đồ vật: 🔍",
  "🔎": "Đồ vật: 🔎",
  "🔬": "Đồ vật: 🔬",
  "🔭": "Đồ vật: 🔭",
  "🔮": "Đồ vật: 🔮",
  "🧿": "Đồ vật: 🧿",
  "🪬": "Đồ vật: 🪬",
  "📿": "Đồ vật: 📿",
  "💰": "Đồ vật: 💰",
  "💴": "Đồ vật: 💴",
  "💵": "Đồ vật: 💵",
  "💶": "Đồ vật: 💶",
  "💷": "Đồ vật: 💷",
  "💳": "Đồ vật: 💳",
  "🧾": "Đồ vật: 🧾",
  "✉": "Đồ vật: ✉",
  "📩": "Đồ vật: 📩",
  "📨": "Đồ vật: 📨",
  "📧": "Đồ vật: 📧",
  "📦": "Đồ vật: 📦",
  "📫": "Đồ vật: 📫",
  "📪": "Đồ vật: 📪",
  "📬": "Đồ vật: 📬",
  "📭": "Đồ vật: 📭",
  "📮": "Đồ vật: 📮",
  "📝": "Đồ vật: 📝",
  "📄": "Đồ vật: 📄",
  "📃": "Đồ vật: 📃",
  "📑": "Đồ vật: 📑",
  "📊": "Đồ vật: 📊",
  "📈": "Đồ vật: 📈",
  "📉": "Đồ vật: 📉",
  "📜": "Đồ vật: 📜",
  "📋": "Đồ vật: 📋",
  "📅": "Đồ vật: 📅",
  "📆": "Đồ vật: 📆",
  "🗂": "Đồ vật: 🗂",
  "📁": "Đồ vật: 📁",
  "📂": "Đồ vật: 📂",
  "🗃": "Đồ vật: 🗃",
  "🗄": "Đồ vật: 🗄",
  "🗑": "Đồ vật: 🗑",
  "🔒": "Đồ vật: 🔒",
  "🔓": "Đồ vật: 🔓",
  "🔏": "Đồ vật: 🔏",
  "🔐": "Đồ vật: 🔐",
  "🔑": "Đồ vật: 🔑",
  "🗝": "Đồ vật: 🗝",
  "🔨": "Đồ vật: 🔨",
  "🛠": "Đồ vật: 🛠",
  "⛏": "Đồ vật: ⛏",
  "🔧": "Đồ vật: 🔧",
  "🔩": "Đồ vật: 🔩",
  "⚙": "Đồ vật: ⚙",
  "🧱": "Đồ vật: 🧱",
  "⛓": "Đồ vật: ⛓",
  "🧲": "Đồ vật: 🧲",
  "🔫": "Đồ vật: 🔫",
  "💣": "Đồ vật: 💣",
  "🧨": "Đồ vật: 🧨",
  "🪓": "Đồ vật: 🪓",
  "🔪": "Đồ vật: 🔪",
  "🗡": "Đồ vật: 🗡",
  "⚔": "Đồ vật: ⚔",
  "🛡": "Đồ vật: 🛡",
  "🚬": "Đồ vật: 🚬",
  "⚰": "Đồ vật: ⚰",
  "⚱": "Đồ vật: ⚱",
  "🏺": "Đồ vật: 🏺",
  "🧪": "Đồ vật: 🧪",
  "🧫": "Đồ vật: 🧫",
  "🧬": "Đồ vật: 🧬",
  "🚪": "Đồ vật: 🚪",
  "🪞": "Đồ vật: 🪞",
  "🪟": "Đồ vật: 🪟",
  "🛏": "Đồ vật: 🛏",
  "🛋": "Đồ vật: 🛋",
  "🪑": "Đồ vật: 🪑",
  "🚽": "Đồ vật: 🚽",
  "🚿": "Đồ vật: 🚿",
  "🛁": "Đồ vật: 🛁",
  "🪤": "Đồ vật: 🪤",
  "🪒": "Đồ vật: 🪒",
  "🧴": "Đồ vật: 🧴",
  "🧷": "Đồ vật: 🧷",
  "🧹": "Đồ vật: 🧹",
  "🧺": "Đồ vật: 🧺",
  "🧻": "Đồ vật: 🧻",
  "🧼": "Đồ vật: 🧼",
  "🧽": "Đồ vật: 🧽",
  "🧯": "Đồ vật: 🧯",
  "🛒": "Đồ vật: 🛒",
  "🧳": "Đồ vật: 🧳",
  "🛎": "Đồ vật: 🛎",
  "❤️": "Biểu tượng: ❤️",
  "🖤": "Biểu tượng: 🖤",
  "🤍": "Biểu tượng: 🤍",
  "🤎": "Biểu tượng: 🤎",
  "❣️": "Biểu tượng: ❣️",
  "☮": "Biểu tượng: ☮",
  "✝": "Biểu tượng: ✝",
  "☪": "Biểu tượng: ☪",
  "🕉": "Biểu tượng: 🕉",
  "☸": "Biểu tượng: ☸",
  "✡": "Biểu tượng: ✡",
  "🔯": "Biểu tượng: 🔯",
  "🕎": "Biểu tượng: 🕎",
  "☯": "Biểu tượng: ☯",
  "☦": "Biểu tượng: ☦",
  "🛐": "Biểu tượng: 🛐",
  "⛎": "Biểu tượng: ⛎",
  "♈": "Biểu tượng: ♈",
  "♉": "Biểu tượng: ♉",
  "♊": "Biểu tượng: ♊",
  "♋": "Biểu tượng: ♋",
  "♌": "Biểu tượng: ♌",
  "♍": "Biểu tượng: ♍",
  "♎": "Biểu tượng: ♎",
  "♏": "Biểu tượng: ♏",
  "♐": "Biểu tượng: ♐",
  "♑": "Biểu tượng: ♑",
  "♒": "Biểu tượng: ♒",
  "♓": "Biểu tượng: ♓",
  "🆔": "Biểu tượng: 🆔",
  "⚛": "Biểu tượng: ⚛",
  "☣": "Biểu tượng: ☣",
  "☢": "Biểu tượng: ☢",
  "📴": "Biểu tượng: 📴",
  "📳": "Biểu tượng: 📳",
  "🈶": "Biểu tượng: 🈶",
  "🈚": "Biểu tượng: 🈚",
  "🈸": "Biểu tượng: 🈸",
  "🈺": "Biểu tượng: 🈺",
  "🈷": "Biểu tượng: 🈷",
  "✴": "Biểu tượng: ✴",
  "🆚": "Biểu tượng: 🆚",
  "💮": "Biểu tượng: 💮",
  "🉐": "Biểu tượng: 🉐",
  "㊙": "Biểu tượng: ㊙",
  "㊗": "Biểu tượng: ㊗",
  "🈴": "Biểu tượng: 🈴",
  "🈵": "Biểu tượng: 🈵",
  "🈹": "Biểu tượng: 🈹",
  "🈲": "Biểu tượng: 🈲",
  "🅰": "Biểu tượng: 🅰",
  "🅱": "Biểu tượng: 🅱",
  "🆎": "Biểu tượng: 🆎",
  "🆑": "Biểu tượng: 🆑",
  "🅾": "Biểu tượng: 🅾",
  "🆘": "Biểu tượng: 🆘",
  "❌": "Biểu tượng: ❌",
  "⭕": "Biểu tượng: ⭕",
  "🛑": "Biểu tượng: 🛑",
  "⛔": "Biểu tượng: ⛔",
  "📛": "Biểu tượng: 📛",
  "🚫": "Biểu tượng: 🚫",
  "💯": "Biểu tượng: 💯",
  "💢": "Biểu tượng: 💢",
  "♨": "Biểu tượng: ♨",
  "🚷": "Biểu tượng: 🚷",
  "🚯": "Biểu tượng: 🚯",
  "🚳": "Biểu tượng: 🚳",
  "🚱": "Biểu tượng: 🚱",
  "🔞": "Biểu tượng: 🔞",
  "📵": "Biểu tượng: 📵",
  "🚭": "Biểu tượng: 🚭",
  "❗": "Biểu tượng: ❗",
  "❕": "Biểu tượng: ❕",
  "❓": "Biểu tượng: ❓",
  "❔": "Biểu tượng: ❔",
  "‼": "Biểu tượng: ‼",
  "⁉": "Biểu tượng: ⁉",
  "🔅": "Biểu tượng: 🔅",
  "🔆": "Biểu tượng: 🔆",
  "〽": "Biểu tượng: 〽",
  "⚠️": "Biểu tượng: ⚠️",
  "🚸": "Biểu tượng: 🚸",
  "🔱": "Biểu tượng: 🔱",
  "⚜": "Biểu tượng: ⚜",
  "🔰": "Biểu tượng: 🔰",
  "♻": "Biểu tượng: ♻",
  "✅": "Biểu tượng: ✅",
  "🈯": "Biểu tượng: 🈯",
  "💹": "Biểu tượng: 💹",
  "❇": "Biểu tượng: ❇",
  "✳": "Biểu tượng: ✳",
  "❎": "Biểu tượng: ❎",
  "💠": "Biểu tượng: 💠",
  "Ⓜ": "Biểu tượng: Ⓜ",
  "💤": "Biểu tượng: 💤",
  "🚾": "Biểu tượng: 🚾",
  "♿": "Biểu tượng: ♿",
  "🅿": "Biểu tượng: 🅿",
  "🈳": "Biểu tượng: 🈳",
  "🈂": "Biểu tượng: 🈂",
  "🛂": "Biểu tượng: 🛂",
  "🛃": "Biểu tượng: 🛃",
  "🛄": "Biểu tượng: 🛄",
  "🛅": "Biểu tượng: 🛅",
  "🚹": "Biểu tượng: 🚹",
  "🚺": "Biểu tượng: 🚺",
  "🚼": "Biểu tượng: 🚼",
  "🚻": "Biểu tượng: 🚻",
  "🚮": "Biểu tượng: 🚮",
  "🎦": "Biểu tượng: 🎦",
  "📶": "Biểu tượng: 📶",
  "🈁": "Biểu tượng: 🈁",
  "🆖": "Biểu tượng: 🆖",
  "🆗": "Biểu tượng: 🆗",
  "🆙": "Biểu tượng: 🆙",
  "🆒": "Biểu tượng: 🆒",
  "🆕": "Biểu tượng: 🆕",
  "🆓": "Biểu tượng: 🆓",
  "🔟": "Biểu tượng: 🔟",
  "🔢": "Biểu tượng: 🔢",
  "🔣": "Biểu tượng: 🔣",
  "🔤": "Biểu tượng: 🔤",
  "🔡": "Biểu tượng: 🔡",
  "🔠": "Biểu tượng: 🔠",
  "ℹ": "Biểu tượng: ℹ",
  "▶": "Biểu tượng: ▶",
  "◀": "Biểu tượng: ◀",
  "🔼": "Biểu tượng: 🔼",
  "🔽": "Biểu tượng: 🔽",
  "⏩": "Biểu tượng: ⏩",
  "⏪": "Biểu tượng: ⏪",
  "⏫": "Biểu tượng: ⏫",
  "⏬": "Biểu tượng: ⏬",
  "➡️": "Biểu tượng: ➡️",
  "⬅️": "Biểu tượng: ⬅️",
  "⬆️": "Biểu tượng: ⬆️",
  "⬇️": "Biểu tượng: ⬇️",
  "↗️": "Biểu tượng: ↗️",
  "↘️": "Biểu tượng: ↘️",
  "↙️": "Biểu tượng: ↙️",
  "↖️": "Biểu tượng: ↖️",
  "↕️": "Biểu tượng: ↕️",
  "↔️": "Biểu tượng: ↔️",
  "🔄": "Biểu tượng: 🔄",
  "↪️": "Biểu tượng: ↪️",
  "↩️": "Biểu tượng: ↩️",
  "⤴️": "Biểu tượng: ⤴️",
  "⤵️": "Biểu tượng: ⤵️",
  "🔀": "Biểu tượng: 🔀",
  "🔁": "Biểu tượng: 🔁",
  "🔂": "Biểu tượng: 🔂",
  "➕": "Biểu tượng: ➕",
  "➖": "Biểu tượng: ➖",
  "➗": "Biểu tượng: ➗",
  "✖️": "Biểu tượng: ✖️",
  "♾": "Biểu tượng: ♾",
  "💲": "Biểu tượng: 💲",
  "💱": "Biểu tượng: 💱",
  "™": "Biểu tượng: ™",
  "©": "Biểu tượng: ©",
  "®": "Biểu tượng: ®",
  "👁️‍🗨️": "Biểu tượng: 👁️‍🗨️",
  "🔘": "Biểu tượng: 🔘",
  "🔴": "Biểu tượng: 🔴",
  "🟠": "Biểu tượng: 🟠",
  "🟡": "Biểu tượng: 🟡",
  "🟢": "Biểu tượng: 🟢",
  "🔵": "Biểu tượng: 🔵",
  "🟣": "Biểu tượng: 🟣",
  "⚫": "Biểu tượng: ⚫",
  "⚪": "Biểu tượng: ⚪",
  "🟤": "Biểu tượng: 🟤",
  "🔺": "Biểu tượng: 🔺",
  "🔻": "Biểu tượng: 🔻",
  "🔸": "Biểu tượng: 🔸",
  "🔹": "Biểu tượng: 🔹",
  "🔶": "Biểu tượng: 🔶",
  "🔷": "Biểu tượng: 🔷",
  "🔳": "Biểu tượng: 🔳",
  "🔲": "Biểu tượng: 🔲",
  "▪️": "Biểu tượng: ▪️",
  "▫️": "Biểu tượng: ▫️",
  "◾": "Biểu tượng: ◾",
  "◽": "Biểu tượng: ◽",
  "◼️": "Biểu tượng: ◼️",
  "◻️": "Biểu tượng: ◻️",
  "⬛": "Biểu tượng: ⬛",
  "⬜": "Biểu tượng: ⬜",
  "🔈": "Biểu tượng: 🔈",
  "🔉": "Biểu tượng: 🔉",
  "🔊": "Biểu tượng: 🔊",
  "🔇": "Biểu tượng: 🔇",
  "🔔": "Biểu tượng: 🔔",
  "🔕": "Biểu tượng: 🔕",
  "📣": "Biểu tượng: 📣",
  "📢": "Biểu tượng: 📢",
  "💬": "Biểu tượng: 💬",
  "💭": "Biểu tượng: 💭",
  "🗯": "Biểu tượng: 🗯",
  "♠️": "Biểu tượng: ♠️",
  "♣️": "Biểu tượng: ♣️",
  "♥️": "Biểu tượng: ♥️",
  "♦️": "Biểu tượng: ♦️",
  "🃏": "Biểu tượng: 🃏",
  "🎴": "Biểu tượng: 🎴",
  "🇮🇹": "Cờ các quốc gia: 🇮🇹",
  "🇪🇸": "Cờ các quốc gia: 🇪🇸",
  "🇷🇺": "Cờ các quốc gia: 🇷🇺",
  "🇧🇷": "Cờ các quốc gia: 🇧🇷",
  "🇨🇦": "Cờ các quốc gia: 🇨🇦",
  "🇦🇺": "Cờ các quốc gia: 🇦🇺",
  "🇮🇳": "Cờ các quốc gia: 🇮🇳",
  "🇹🇭": "Cờ các quốc gia: 🇹🇭",
  "🇸🇬": "Cờ các quốc gia: 🇸🇬",
  "🇲🇾": "Cờ các quốc gia: 🇲🇾",
  "🇮🇩": "Cờ các quốc gia: 🇮🇩",
  "🇵🇭": "Cờ các quốc gia: 🇵🇭",
  "🇱🇦": "Cờ các quốc gia: 🇱🇦",
  "🇰🇭": "Cờ các quốc gia: 🇰🇭",
  "🇲🇲": "Cờ các quốc gia: 🇲🇲",
  "🇧🇳": "Cờ các quốc gia: 🇧🇳",
  "🇵🇹": "Cờ các quốc gia: 🇵🇹",
  "🇲🇽": "Cờ các quốc gia: 🇲🇽",
  "🇦🇷": "Cờ các quốc gia: 🇦🇷",
  "🇨🇭": "Cờ các quốc gia: 🇨🇭",
  "🇸🇪": "Cờ các quốc gia: 🇸🇪",
  "🇳🇴": "Cờ các quốc gia: 🇳🇴",
  "🇩🇰": "Cờ các quốc gia: 🇩🇰",
  "🇫🇮": "Cờ các quốc gia: 🇫🇮",
  "🇳🇱": "Cờ các quốc gia: 🇳🇱",
  "🇧🇪": "Cờ các quốc gia: 🇧🇪",
  "🇦🇹": "Cờ các quốc gia: 🇦🇹",
  "🇬🇷": "Cờ các quốc gia: 🇬🇷",
  "🇹🇷": "Cờ các quốc gia: 🇹🇷",
  "🇸🇦": "Cờ các quốc gia: 🇸🇦",
  "🇦🇪": "Cờ các quốc gia: 🇦🇪",
  "🇪🇬": "Cờ các quốc gia: 🇪🇬",
  "🇿🇦": "Cờ các quốc gia: 🇿🇦",
  "🇳🇿": "Cờ các quốc gia: 🇳🇿",
  "🏳️": "Cờ các quốc gia: 🏳️",
  "🏴": "Cờ các quốc gia: 🏴",
  "🎌": "Cờ các quốc gia: 🎌",
  "🏴‍☠️": "Cờ các quốc gia: 🏴‍☠️",
  "🏳️‍🌈": "Cờ các quốc gia: 🏳️‍🌈",
  "🏳️‍⚧️": "Cờ các quốc gia: 🏳️‍⚧️",
  "🇦": "Cờ các quốc gia: 🇦",
  "🇧": "Cờ các quốc gia: 🇧",
  "🇨": "Cờ các quốc gia: 🇨",
  "🇩": "Cờ các quốc gia: 🇩",
  "🇪": "Cờ các quốc gia: 🇪",
  "🇫": "Cờ các quốc gia: 🇫",
  "🇬": "Cờ các quốc gia: 🇬",
  "🇭": "Cờ các quốc gia: 🇭",
  "🇮": "Cờ các quốc gia: 🇮",
  "🇯": "Cờ các quốc gia: 🇯",
  "🇰": "Cờ các quốc gia: 🇰",
  "🇱": "Cờ các quốc gia: 🇱",
  "🇲": "Cờ các quốc gia: 🇲",
  "🇳": "Cờ các quốc gia: 🇳",
  "🇴": "Cờ các quốc gia: 🇴",
  "🇵": "Cờ các quốc gia: 🇵",
  "🇶": "Cờ các quốc gia: 🇶",
  "🇷": "Cờ các quốc gia: 🇷",
  "🇸": "Cờ các quốc gia: 🇸",
  "🇹": "Cờ các quốc gia: 🇹",
  "🇺": "Cờ các quốc gia: 🇺",
  "🇻": "Cờ các quốc gia: 🇻",
  "🇼": "Cờ các quốc gia: 🇼",
  "🇽": "Cờ các quốc gia: 🇽",
  "🇾": "Cờ các quốc gia: 🇾",
  "🇿": "Cờ các quốc gia: 🇿"
};

export function getEmojiName(emoji: string): string {
  return EMOJI_NAMES[emoji] || `Biểu tượng ${emoji}`;
}

export function searchEmojis(query: string, activeGroupId?: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    if (activeGroupId) {
      const grp = EMOJI_GROUPS.find((g) => g.id === activeGroupId);
      return grp ? grp.emojis : [];
    }
    return EMOJI_GROUPS[0]?.emojis || [];
  }

  const results: string[] = [];
  for (const group of EMOJI_GROUPS) {
    for (const emoji of group.emojis) {
      const name = (EMOJI_NAMES[emoji] || '').toLowerCase();
      if (name.includes(q) || emoji.includes(q)) {
        results.push(emoji);
      }
    }
  }
  return results;
}

export const ALL_EMOJIS_COUNT = EMOJI_GROUPS.reduce((acc, g) => acc + g.emojis.length, 0);
